### ISSUE TITLE
Compatibility with VTO2101E-P 

### ISSUE THREAD

**Issue by farkhad81** [myhomeiot/DahuaVTO#11]
Hi, Im trying to hookup [VTO2101E-P](https://www.dahuasecurity.com/products/productDetail/21847)  thru your integration. However it doesn't seem to work with it. The sensor Dahua VTO displays unknown status. Is there any chance to make this integration happen?
Here is what I found in logs: 
2022-01-02 15:54:50 ERROR (MainThread) [custom_components.dahua_vto.sensor] Dahua VTO: [Errno 113] Connect call failed ('192.168.1.110', 5000), retry in 10 seconds

**Comment by myhomeiot** [comment]
Hello, the VTO2101 should works, check logs, IP/user name/password and you can turn on the [debugging](https://github.com/myhomeiot/DahuaVTO#debugging)
Also check if you can control this VTO using Dahua DMSS application.

**Comment by myhomeiot** [comment]
> 2022-01-02 15:54:50 ERROR (MainThread) [custom_components.dahua_vto.sensor] Dahua VTO: [Errno 113] Connect call failed ('192.168.1.110', 5000), retry in 10 seconds

Looks like it's doesn't reply on port tcp/5000, check if Dahua DMSS application works.

**Comment by farkhad81** [comment]
> debugging

Yes, I was able to connect with gDMSS., Ports seem to be open as well:
Connection to 192.168.1.110 port 5000 [tcp/commplex-main] succeeded!

**Comment by myhomeiot** [comment]
> Connection to 192.168.1.110 port 5000 [tcp/commplex-main] succeeded!

Check if the system where integration installed can connect to port 5000 of 192.168.1.110. Turn in debugging and look for other messages, it's may help you to understand whats going wrong.

**Comment by farkhad81** [comment]
Turning OFF VLAN Segmentation on my PoE switch happen to fix the issue :) Thanks for your assistance in troubleshooting and for your great plugin!

**Comment by myhomeiot** [comment]
Glad that integration works for you. Happy New Year!
