### ISSUE TITLE
Missing feature list

### ISSUE THREAD

**Issue by majuss** [myhomeiot/DahuaVTO#16]
Sorry to bother but I'am currently looking into video doorbells and Dahua seems to be a very attractive candidate.
I'am missing a feature list, what the integration can do with the doorbell. As far as I understood it's the following:
What it can do in HA:
- show when somebody rang the bell
- if calls got answered
- lock/unlock (this seems a bit useless if you're using HA)

What it can't do:
- show video from the bell in HA
- Answering SIP ring calls

Is my understanding correct? Can I setup another RTSP component in HA to get the video? And a SIP server and client for the calls?

**Comment by myhomeiot** [comment]
Yes, for video from doorbell you can use Generic Camera/RTSP/ONVIF integration, for SIP you can use **azelphur** solution described [here](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/91?u=myhomeiot)
