### ISSUE TITLE
Automation with video door entry call.

### ISSUE THREAD

**Issue by romero091** [myhomeiot/DahuaVTO#18]
Good afternoon. I have configured the integration in HA but I am a bit lost in programming.
I would like to know if an automation could be configured so that when calling the video intercom, it turns on a light for 1 minute.

Any sample code, if anyone has done it?

Thanks

**Comment by myhomeiot** [comment]
Please ask in [this](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693) thread.
