### ISSUE TITLE
States al the time ok

### ISSUE THREAD

**Issue by Marcmk1** [myhomeiot/DahuaVTO#2]
The state is al the time, ok
got an: VTO2101E-P-S1

When I change the state in HomeAssistant through Developper, the state jumps back to OK.
So when I push the doorbel nothing happens to the state.

**Comment by myhomeiot** [comment]
Status of the sensor shows if communication with device is OK.
If you want to get notified when doorbell rings you should configure events, see example [here](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events)

**Comment by myhomeiot** [comment]
Let's me know here if you get it working with VTO2101E-P-S1 or if you get a problems.
