### ISSUE TITLE
VTH

### ISSUE THREAD

**Issue by MooseGmaing** [myhomeiot/DahuaVTO#21]
Hi,
I'm using the Dahua 2421 VTH and want to integrate it into HA. The only thing is my Home Assistant does not recognize a `dahua_vth` integration.

I can't find anything about using VTHs in your documentation, even though they are listed as supported.

**Comment by myhomeiot** [comment]
Hello,

For VTH you should use same integration `dahua_vto` just specify user name `admin` and password which you use for access settings menu at VTH, example:
```
  - platform: dahua_vto
    name: Dahua VTH
    host: 192.168.1.41
    username: admin
    password: 123456
```

Usually you can't do much with VTH but in [readme](https://github.com/myhomeiot/DahuaVTO) if you search `VTH` you will see some examples like Clear VTH Call Records, Arming the VTH alarm, ect.

Hope this helps.

**Comment by MooseGmaing** [comment]
Thanks,
I have the VTH sensor working; I am using the `VTH2421`, so you can add that to your list of supported devices.


I also have another problem. The last time my VTO responded (to Home Assistant) was 7 hours ago, even though I set the `scan_interval` to 1. (the VTH also doesn't respond often)

Does your door lock automation script let me control the door lock, or does it just show me its status? I'm asking as when I click on `door_lock,` I get two buttons, `UNLOCK` and `LOCK,` but when I press them, nothing happens, and `door_lock` is marked as `read only` in the HA settings.

**Comment by myhomeiot** [comment]
About VTO/VTH last response - you should check the `state` of the sensor and not last changed time. If state is `OK`, everything works. Inside protocol Dahua devices has heartbeat, so if HA lost connectivity with device - state of the device sensor will be changed to `ERROR`. `scan_interval` define the interval when HA update state from integration and this will not force any messages to device itself. You can remove this parameter and use default 60 sec interval.

Door lock should work, as you can see [here](https://github.com/myhomeiot/DahuaVTO#lock-example-with-call-to-open-door-service) it’s communicate with VTO only on UNLOCK command, and use `timer.door_lock` for count time of unlock duration [when](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events) receives state [8](https://github.com/myhomeiot/DahuaVTO#backkeylight-states). You can check/set the duration of unlock in VTO web GUI. In order to check if your VTO opens the door lock you can use `open_door` service from HA Developer Tools -> Services panel and check if you can open the door lock. Use channel 1 or 2 depend how your door lock connected to VTO.

You can also find some discussions about door lock in this [thread](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693).

**Comment by MooseGmaing** [comment]
I can't get the lock working. It also shows up weirdly when I click on it.
![Dahua](https://user-images.githubusercontent.com/106101028/231560882-6939caf1-d684-4379-9186-7520ba7f81ba.PNG)
^ That is the lock, and here you have my water pump:
![Water Pump](https://user-images.githubusercontent.com/106101028/231561086-4d0e8b0c-bc75-42b1-aea7-367679fc7dec.PNG)

**Comment by myhomeiot** [comment]
Can you open the lock using Dahua DMSS application? Which lock icon from application do you use 1st or 2nd?
If in DMSS application you can open the lock, than you can enable integration [debugging](https://github.com/myhomeiot/DahuaVTO#debugging) and post here the log.

"shows up weirdly" it's depends from Home Assistant, currently it's shows lock like this.

**Comment by MooseGmaing** [comment]
Hi,
I cannot control the lock from the DMSS app. The VTO2111 I use may not support this feature, but I can control the lock from the VTH.
Here's my VTO config (maybe I don't have the default settings, and that is causing the problem).
![VTO](https://user-images.githubusercontent.com/106101028/231815979-ff0b4a93-e948-49f8-8518-9fcdc374347c.PNG)

**Comment by myhomeiot** [comment]
I also has VTO2111D and I can connect this VTO to Dahua DMSS mobile application and control the lock. I can't control the lock from VTO Web GUI, only make settings:

![image](https://user-images.githubusercontent.com/70070601/231905153-a5eedd7a-1226-454d-b067-e5596c8e71b3.png)

**Comment by DNA99** [comment]
Did u check that uPNP is enabled?

**Comment by MooseGmaing** [comment]
Hello,
I didn't have UPnP enabled, but I now do, and this is what I get (look at the photo below). I don't know why, but everything says that it failed.
![uPNP](https://user-images.githubusercontent.com/106101028/232134159-c1ce8f36-591a-4510-a313-416addca0d37.PNG)

**Comment by MooseGmaing** [comment]
To be clear, even though everything is supposedly not working, I can access my camera from HA no problem.

**Comment by myhomeiot** [comment]
@MooseGmaing Camera in VTO use RTSP and works independent. Dahua DMSS application can work over cloud and locally, for cloud setup you will need UPnP, but if you don't wont cloud you don't need UPnP. For local setup in DMSS application add VTO by specifying local IP, user name and password.

If you have spare time and you home can work for some time without VTO I recommend to backup current configuration, write down the current firmware versions, update VTO and VTH firmware's for latest versions and try to setup it from scratch. It's will give you more understanding about how this works and you will get proper setup. Personal I did same after year of time to time playing with the settings and trying to understand how this works. The starting point for me was this [video](https://youtu.be/Z3QhTU9dt6Y). Latest firmwares you can search in Dahua web site, for my `VTO2111D-WP-S1` I use `General_VTO2111D_Eng_P_16M_SIP_V4.300.0000000.7.R.20200311.zip`

**Comment by MooseGmaing** [comment]
Hi, I actually did this less than a month ago. The technicians were dumb and set the IPs of the VTO and VTHs outside my IP range (as you see, I have a `10.0.0.x` system, and they used `192.168.1.x`!). So I redid the whole config and set the correct IP addresses. I did this initially to access the camera in the VTO, but last weekend I installed HACS and found out about this integration.

The thing I can do is the firmware update. My firmware is `V4.2` if I recall correctly. I'll update it and let you know how it went.

**Comment by MooseGmaing** [comment]
Ok, update here, the lock works (when I press the button in HA, I can open my gate). The only thing is the status on HA doesn't change (it still says it is locked). In this case, I don't need much more. 

Is there any way of making this entity a button (instead of lock and unlock, I click the button to open the gate)? I also wouldn't need to get the status of the lock.

**Comment by myhomeiot** [comment]
Status of the lock doesn't changes because it's depends from timer which starts [here](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events) on unlock event.
Sure you can simple make it as a button using HA button template:

```
template:
  - button:
      - name: Door Lock
        press:
          - service: dahua_vto.open_door
            data_template:
              entity_id: sensor.dahua_vto
              channel: 1
              short_number: HA
```

**Comment by MooseGmaing** [comment]
Thanks! Works perfectly. 
The only problem is that the old door lock entity is still here (even after I deleted the old YAML code), and I can't remove it from the GUI.
How can I remove it? Also, I'd like to hide the timer entity.

**Comment by myhomeiot** [comment]
If you don't need the lock you can also remove the timer from YAML code. After restarting HA you should be able to delete the lock and timer entities from Settings -> Device & Services -> Entities menu.

**Comment by MooseGmaing** [comment]
Ok, thank you for ALL the help :)
