### ISSUE TITLE
2 wire ip VTH2622

### ISSUE THREAD

**Issue by harisma-git** [myhomeiot/DahuaVTO#23]
Hi there.  Can i open the door from Home Assistant if i have only access to the appartment VTH2622 station and not to the outdoor station? VTH is connected to my wifi network to give access to DMSS.

**Comment by myhomeiot** [comment]
Hello, can you open door from DMSS?

**Comment by harisma-git** [comment]
yeap

**Comment by myhomeiot** [comment]
I try to connect my VTH5221D into DMSS without success, maybe it's not supported or I should be logged in into Dahua Cloud (I use VTO/VTH locally and even disable internet access for them).

But you can try to issue command `od` (open door) from integration directly to VTH maybe it's will work for your VTH2622. More details about commands and testing you can found in this [post](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/279?u=myhomeiot).

Let's me know if you find solution.

**Comment by myhomeiot** [comment]
@harisma-git Any news?
