### ISSUE TITLE
it´s posible to get the card number?

### ISSUE THREAD

**Issue by luisrival** [myhomeiot/DahuaVTO#25]
Hi.

I also use my VTO as access control, so i was wondering if there is a way to get the card id/number of the cards that we use to open the door

Great project!

**Comment by myhomeiot** [comment]
`trigger.event.data.Data.CardNo`, please check [this](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/241?u=myhomeiot) thread for more information.

**Comment by luisrival** [comment]
awesome! thanks
