### ISSUE TITLE
VTO2202 - Video Intercom Button Pressed no longer working

### ISSUE THREAD

**Issue by boozelclark** [myhomeiot/DahuaVTO#29]
Hi

In the last few days i have noticed that when the intercom button on my VTO2202 is pressed I no longer see the entitiy change in Home Assistant. I have firmware version 2022-05-23 V4.511.0000000.0.R and in my logs i get the following:

Warning:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 17:24:19 (4 occurrences)
Last logged: 17:24:49

Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 365: listener(), please report it to the author of the 'dahua' custom integration
Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 382: listener(), please report it to the author of the 'dahua' custom integration

Quickly followed by:

Error:
Logger: custom_components.dahua
Source: custom_components/dahua/vto.py:119
integration: Dahua ([documentation](https://github.com/rroller/dahua), [issues](https://github.com/rroller/dahua/issues))
First occurred: 17:24:19 (4 occurrences)
Last logged: 17:24:49

Failed to handle event, error: Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 365: listener(). Please report it to the author of the 'dahua' custom integration., Line: 114
Failed to handle event, error: Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 382: listener(). Please report it to the author of the 'dahua' custom integration., Line: 114

Is anyone else experiencing similar issues? Any help would be much appreciated.

Thanks,

**Comment by myhomeiot** [comment]
Hello, you probably mixed up the integration and are using this [one](https://github.com/rroller/dahua).
Your issue looks similar to this [issue](https://github.com/rroller/dahua/issues/352)

**Comment by boozelclark** [comment]
Thanks very much! I'm not sure how i got the two mixed up. The one I had installed vs the one i had installed via HACS was different some how.
