### ISSUE TITLE
2 way audio

### ISSUE THREAD

**Issue by weitheng** [myhomeiot/DahuaVTO#3]
Does this support 2-way audio on Home assistant? Or does it still have to be done through a different app?

**Comment by myhomeiot** [comment]
This protocol doesn't support audio, maybe you can get audio endpoints using some VTO commands and then configure rtsp/rtp for it using different Home Assistant component. How to use commands you can read [here](https://github.com/myhomeiot/DahuaVTO#some-command-examples)

You can also try to configure SIP server and than you will get call to your SIP client when some one will ring the bell.

Please continue discussion [here](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/4)
