### ISSUE TITLE
Error when using a Lorek 1080p doorbell

### ISSUE THREAD

**Issue by CarlosGtrz** [myhomeiot/DahuaVTO#31]
Hi

I undestand Lorex doorbell is not in the list of supported hardware, but wanted to let you know that I've been using your integration with this doorbell and it works. It correctly reports motion person and button events (`VideoMotion`, `SmartMotionHuman` and `CallNoAnswered`).

The only problem is that it constantly reports an error in HA log:

````
Registrador: homeassistant
Fuente: custom_components/dahua_vto/sensor.py:147
integración: Dahua VTO ([documentación](https://github.com/myhomeiot/DahuaVTO), [problemas](https://github.com/myhomeiot/DahuaVTO/issues))
Ocurrió por primera vez: 1:13:00 p. m. (7 ocurrencias)
Último inicio de sesión: 1:14:07 p. m.

Error doing job: Exception in callback _SelectorSocketTransport._call_connection_lost(None) (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1181, in _call_connection_lost
    super()._call_connection_lost(exc)
[home-assistant_2024-07-05T20-14-25.215Z.log](https://github.com/user-attachments/files/16113543/home-assistant_2024-07-05T20-14-25.215Z.log)
[home-assistant_2024-07-05T20-14-25.215Z.log](https://github.com/user-attachments/files/16113547/home-assistant_2024-07-05T20-14-25.215Z.log)


  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 901, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/config/custom_components/dahua_vto/sensor.py", line 147, in connection_lost
    self.on_connection_lost.set_result(True)
asyncio.exceptions.InvalidStateError: invalid state
````

I'm attaching the debug log, in case you want to look into this. I'll be happy to help in any test.

Regards

**Comment by CarlosGtrz** [comment]
[home-assistant_2024-07-05T20-14-25.215Z.log](https://github.com/user-attachments/files/16113559/home-assistant_2024-07-05T20-14-25.215Z.log)

**Comment by myhomeiot** [comment]
Hello,

Interesting why this device has Dahua API ;-)
Looks like Lorek 1080p doorbell doesn't have `configManager` API so you can use previous version of integration [1.0.6](https://github.com/myhomeiot/DahuaVTO/releases/tag/1.0.6) it's should work.

Current version 1.0.7 has just configManager and no other improvements.  Difference you can see [here](https://github.com/myhomeiot/DahuaVTO/commit/7344f5c9574a354bf7e167f54f03f9d6f0f0d8f0)

**Comment by CarlosGtrz** [comment]
Apparently, it's a clone of a Dahua DH-DB6I doorbell. 

Just confirmed that after downgrading to 1.0.6 there are no error messages in the log and the events still work.  Thanks a lot!

**Comment by CarlosGtrz** [comment]
Apparently, it's a clone of a Dahua DH-DB6I doorbell. Just confirmed that after downgrading to 1.0.6 the are no error messages in the log and the events still works.  Thanks a lot!

**Comment by myhomeiot** [comment]
Great! Keep using this version, in next version, if I get something to change, I will make `configManager` API as optional.

**Comment by myhomeiot** [comment]
@CarlosGtrz you can update to [1.0.8](https://github.com/myhomeiot/DahuaVTO/releases/tag/1.0.8) and add `config_manager_attach` into configuration as it's shown in example:

```yaml
  - platform: dahua_vto
    name: Dahua VTO
    host: 192.168.1.2
    username: admin
    password: password
    config_manager_attach: false
    scan_interval: 5
```

**Comment by CarlosGtrz** [comment]
Thank you!
