### ISSUE TITLE
How to clear binary sensor "Call No Answered"

### ISSUE THREAD

**Issue by Protoncek** [myhomeiot/DahuaVTO#32]
Hello!
I'm testing my Dahua VTO2211G-WP and it works, rings in HA... but i can't find a way to clear unanswered calls. When VTO rings and there's no answer binary sensor "Call No Answered" is set and remains set. How to clear it? Or, at least, how (if possible at all) imitate "answer call" in HA? My intention is to use VTO as a doorbell with camera, i won't talk to a visitor (i don't see an easy way to do it... or is it?), i only want to be notified when having a visitor, cancel (receive) call and go out.

Thanks!

**Comment by myhomeiot** [comment]
I don't know what means under binary sensor "Call No Answered" can you provide screenshots, etc.
I know how to clear call records (including unanswered) at VTH and cancel VTO call, you can see specific command [here](https://github.com/myhomeiot/DahuaVTO#some-command-examples), look for `Clear VTH Call Records` and `Cancel VTO Call`

**Comment by myhomeiot** [comment]
I don't know how this integration detects `Call No Answered` but you can use my integration for `Button Pressed` and `Call No Answered` functionality, you can see example [here](https://github.com/myhomeiot/DahuaVTO#automation-example-with-doorbell-ring-and-unlock-events), state 6 it's [`Call not answered`](https://github.com/myhomeiot/DahuaVTO#commands-and-events)

**Comment by Protoncek** [comment]
Yeah, i tried your examples a bit, and i managed to get it to work, thanks. At the end i guess i'll decide to work only with one integration to make things easy. I think i might even disregard that sensor. Nonetheless, there are other ways to remember unanswered calls (with helpers).
Many thanks for your help!

**Comment by myhomeiot** [comment]
Glad it helped you!
