### ISSUE TITLE
warning in version 2024.9

### ISSUE THREAD

**Issue by pacomm** [myhomeiot/DahuaVTO#33]
In the latest version this warning appears:

- Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 99: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues
- Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 104: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues
- Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 109: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues

**Comment by KrzysiekLegnica** [comment]
In the latest version this warning appears:

Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 99: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues
Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 104: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues
Detected that custom integration 'dahua_vto' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/dahua_vto/sensor.py, line 109: platform.async_register_entity_service(, please create a bug report at https://github.com/myhomeiot/DahuaVTO/issues
