### ISSUE TITLE
DHI-VTO2211G-WP factory reset

### ISSUE THREAD

**Issue by sdesalve** [myhomeiot/DahuaVTO#37]
Hi I own a  DHI-VTO2211G-WP Dahua Doorbell,

many times it will reset to default factory settings and ask me to set password and email to recover password when I try to login in web gui.

DahuaVTO will stop working because password was not set.
Is this behaviour related to this custom component?
Have someone experiencing same issue?

Best Regards
Salvatore

deviceType: DHI-VTO2211G-WP
serialNumber: 6H0B3F0PA*****
friendly_name: Dahua VTO 

Firmware version: 2024-07-31 V4.511.0000000.1.R

auto_update: false
display_precision: 0
installed_version: 1.0.9
in_progress: false
latest_version: 1.0.9
release_summary: null
release_url: https://github.com/myhomeiot/DahuaVTO/releases/1.0.9
skipped_version: null
title: null
update_percentage: null
entity_picture: https://brands.home-assistant.io/_/dahua_vto/icon.png
friendly_name: Dahua VTO update
supported_features: 23

**Comment by myhomeiot** [comment]
Hello, I never hear about similar problem before. If it's happened it's can be power stability problem or firmware problem, you can try to upgrade/downgrade firmware and see if it's helps.

You can also use state of sensor from this integration to monitor availability of your DHI-VTO2211G-WP, add automatization which monitor state of the sensor and notify you when it's changed, I hope this will help to better understand the problem. By default device will restarts every week, you should see this configuration at web GUI.
