### ISSUE TITLE
help to use this code with VTO1220A and VTO6210

### ISSUE THREAD

**Issue by MohamedHusseinAhmed** [myhomeiot/DahuaVTO#4]
Hello,
Could you please help me ? How to use this code to communicate with "VTO1220A and VTO6210"?
I will use them with raspberry pi and flutter (android) application.
for VTO6210 I need to receive a door bill ring, answer it, talk a video call
for VTO1220 I need to receive a call by room number, answer it, talk a video call
Thanks

**Comment by myhomeiot** [comment]
Hello, this integration doesn't support audio and video. Video from VTO you can get using [generic](https://www.home-assistant.io/integrations/generic) Home Assistant integration or [amcrest](https://www.home-assistant.io/integrations/amcrest) integration. Bidirectional audio you probably can get if you [setup](https://community.home-assistant.io/t/dahua-vto-custom-integration/293693/4?u=myhomeiot) SIP server.

If you have problems/questions with configuring this integration to work with your VTOs, please enable [debugging](https://github.com/myhomeiot/DahuaVTO#debugging) check logs and post your problems/questions at this [forum](https://community.home-assistant.io/t/dahua-vto-custom-integration)
