### ISSUE TITLE
Can not unlock

### ISSUE THREAD

**Issue by gennadys72** [myhomeiot/DahuaVTO#8]
Hello,

Not sure it's related, but with the latest upgrade of the HA core to core-2021.9.3, the unlock function stopped working.
Events from the door panel are received just fine.
This no longer works:
- platform: dahua_vto
  name: Dahua VTO
  host: 192.168.XX.XX
  username: !secret dahua_username
  password: !secret dahua_password
  scan_interval: 5

service: dahua_vto.open_door
data:
  entity_id: sensor.dahua_vto
  channel: 1
  short_number: HA

This still does:
shell_command:
  dahua_vto_open_door: curl -s --globoff --digest --user admin:XXXXX "http://192.168.XX.XX/cgi-bin/accessControl.cgi?action=openDoor&channel=1&UserID=101&Type=Remote"

There's nothing special in the logs (even though i've not enabled any debug).
Panel type VTO3221D

**Comment by myhomeiot** [comment]
In early 1.0.5 version of integration was small bug with channel index, please reinstall 1.0.5 version, or just uninstall and install again. Sorry for inconvenience.

**Comment by gennadys72** [comment]
Indeed, reinstalling seems to help. Thanks!
